package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BlocksId generated by hbm2java
 */
@Embeddable
public class BlocksId implements java.io.Serializable {

	private String loaiCuocgoi;
	private String nhamangId;
	private String maCuocgoi;

	public BlocksId() {
	}

	public BlocksId(String loaiCuocgoi, String nhamangId, String maCuocgoi) {
		this.loaiCuocgoi = loaiCuocgoi;
		this.nhamangId = nhamangId;
		this.maCuocgoi = maCuocgoi;
	}

	@Column(name = "loai_cuocgoi", nullable = false, length = 2)
	public String getLoaiCuocgoi() {
		return this.loaiCuocgoi;
	}

	public void setLoaiCuocgoi(String loaiCuocgoi) {
		this.loaiCuocgoi = loaiCuocgoi;
	}

	@Column(name = "nhamang_id", nullable = false, length = 5)
	public String getNhamangId() {
		return this.nhamangId;
	}

	public void setNhamangId(String nhamangId) {
		this.nhamangId = nhamangId;
	}

	@Column(name = "ma_cuocgoi", nullable = false, length = 5)
	public String getMaCuocgoi() {
		return this.maCuocgoi;
	}

	public void setMaCuocgoi(String maCuocgoi) {
		this.maCuocgoi = maCuocgoi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BlocksId))
			return false;
		BlocksId castOther = (BlocksId) other;

		return ((this.getLoaiCuocgoi() == castOther.getLoaiCuocgoi()) || (this.getLoaiCuocgoi() != null
				&& castOther.getLoaiCuocgoi() != null && this.getLoaiCuocgoi().equals(castOther.getLoaiCuocgoi())))
				&& ((this.getNhamangId() == castOther.getNhamangId()) || (this.getNhamangId() != null
						&& castOther.getNhamangId() != null && this.getNhamangId().equals(castOther.getNhamangId())))
				&& ((this.getMaCuocgoi() == castOther.getMaCuocgoi()) || (this.getMaCuocgoi() != null
						&& castOther.getMaCuocgoi() != null && this.getMaCuocgoi().equals(castOther.getMaCuocgoi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLoaiCuocgoi() == null ? 0 : this.getLoaiCuocgoi().hashCode());
		result = 37 * result + (getNhamangId() == null ? 0 : this.getNhamangId().hashCode());
		result = 37 * result + (getMaCuocgoi() == null ? 0 : this.getMaCuocgoi().hashCode());
		return result;
	}

}
