package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Blocks generated by hbm2java
 */
@Entity
@Table(name = "blocks", catalog = "billings")
public class Blocks implements java.io.Serializable {

	private BlocksId id;
	private Double block1s;
	private Double block6s;
	private Double block10s;
	private Double block1m;

	public Blocks() {
	}

	public Blocks(BlocksId id) {
		this.id = id;
	}

	public Blocks(BlocksId id, Double block1s, Double block6s, Double block10s, Double block1m) {
		this.id = id;
		this.block1s = block1s;
		this.block6s = block6s;
		this.block10s = block10s;
		this.block1m = block1m;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loaiCuocgoi", column = @Column(name = "loai_cuocgoi", nullable = false, length = 2)),
			@AttributeOverride(name = "nhamangId", column = @Column(name = "nhamang_id", nullable = false, length = 5)),
			@AttributeOverride(name = "maCuocgoi", column = @Column(name = "ma_cuocgoi", nullable = false, length = 5)) })
	public BlocksId getId() {
		return this.id;
	}

	public void setId(BlocksId id) {
		this.id = id;
	}

	@Column(name = "block1s", precision = 22, scale = 0)
	public Double getBlock1s() {
		return this.block1s;
	}

	public void setBlock1s(Double block1s) {
		this.block1s = block1s;
	}

	@Column(name = "block6s", precision = 22, scale = 0)
	public Double getBlock6s() {
		return this.block6s;
	}

	public void setBlock6s(Double block6s) {
		this.block6s = block6s;
	}

	@Column(name = "block10s", precision = 22, scale = 0)
	public Double getBlock10s() {
		return this.block10s;
	}

	public void setBlock10s(Double block10s) {
		this.block10s = block10s;
	}

	@Column(name = "block1m", precision = 22, scale = 0)
	public Double getBlock1m() {
		return this.block1m;
	}

	public void setBlock1m(Double block1m) {
		this.block1m = block1m;
	}

}
