package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Congty generated by hbm2java
 */
@Entity
@Table(name = "congty")
public class Congty implements java.io.Serializable {

	private String congtyId;
	private String tenCongty;
	private String logo;
	private String masoThue;
	private String diaChi;
	private String dienthoai;
	private String email;
	private Double tiLeMakeUp;
	private Set<Dauso> dausos = new HashSet<Dauso>(0);
	private Set<Phongban> phongbans = new HashSet<Phongban>(0);
	private Set<TaikhoanNguoidung> taikhoanNguoidungs = new HashSet<TaikhoanNguoidung>(0);

	public Congty() {
	}

	public Congty(String congtyId) {
		this.congtyId = congtyId;
	}

	public Congty(String congtyId, String tenCongty, String logo, String masoThue, String diaChi, String dienthoai,
			String email, Double tiLeMakeUp, Set<Dauso> dausos, Set<Phongban> phongbans,
			Set<TaikhoanNguoidung> taikhoanNguoidungs) {
		this.congtyId = congtyId;
		this.tenCongty = tenCongty;
		this.logo = logo;
		this.masoThue = masoThue;
		this.diaChi = diaChi;
		this.dienthoai = dienthoai;
		this.email = email;
		this.tiLeMakeUp = tiLeMakeUp;
		this.dausos = dausos;
		this.phongbans = phongbans;
		this.taikhoanNguoidungs = taikhoanNguoidungs;
	}

	@Id

	@Column(name = "congtyID", unique = true, nullable = false, length = 10)
	public String getCongtyId() {
		return this.congtyId;
	}

	public void setCongtyId(String congtyId) {
		this.congtyId = congtyId;
	}

	@Column(name = "ten_congty", length = 65535)
	public String getTenCongty() {
		return this.tenCongty;
	}

	public void setTenCongty(String tenCongty) {
		this.tenCongty = tenCongty;
	}

	@Column(name = "logo", length = 65535)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "maso_thue", length = 65535)
	public String getMasoThue() {
		return this.masoThue;
	}

	public void setMasoThue(String masoThue) {
		this.masoThue = masoThue;
	}

	@Column(name = "dia_chi", length = 65535)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "dienthoai", length = 65535)
	public String getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(String dienthoai) {
		this.dienthoai = dienthoai;
	}

	@Column(name = "email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ti_le_make_up", precision = 22, scale = 0)
	public Double getTiLeMakeUp() {
		return this.tiLeMakeUp;
	}

	public void setTiLeMakeUp(Double tiLeMakeUp) {
		this.tiLeMakeUp = tiLeMakeUp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "congty")
	public Set<Dauso> getDausos() {
		return this.dausos;
	}

	public void setDausos(Set<Dauso> dausos) {
		this.dausos = dausos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "congty")
	public Set<Phongban> getPhongbans() {
		return this.phongbans;
	}

	public void setPhongbans(Set<Phongban> phongbans) {
		this.phongbans = phongbans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "congty")
	public Set<TaikhoanNguoidung> getTaikhoanNguoidungs() {
		return this.taikhoanNguoidungs;
	}

	public void setTaikhoanNguoidungs(Set<TaikhoanNguoidung> taikhoanNguoidungs) {
		this.taikhoanNguoidungs = taikhoanNguoidungs;
	}

}
