package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Congty generated by hbm2java
 */
@Entity(name ="congty")
public class Congty implements java.io.Serializable {
@Id
	private String congtyId;
	@OneToMany(fetch = FetchType.EAGER, cascade = { CascadeType.ALL })
	@JoinColumn(name = "congtyId")

//@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
//@JoinColumn(name ="congtyID")
//
//
//
//@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL})
//@JoinColumn(name ="congtyID")
	private String tenCongty;
	private String logo;
	private String masoThue;
	private String diaChi;
	private String dienthoai;
	private String email;
	private Double tiLeMakeUp;
	
//	private Set<Dauso> dausos = new HashSet<Dauso>(0);
//	private Set<Phongban> phongbans = new HashSet<Phongban>(0);
//	private Set<TaikhoanNguoidung> taikhoanNguoidungs = new HashSet<TaikhoanNguoidung>(0);

	
	public Congty(String congtyId, String tenCongty, String logo, String masoThue, String diaChi, String dienthoai,
			String email, Double tiLeMakeUp) {
		this.congtyId = congtyId;
		this.tenCongty = tenCongty;
		this.logo = logo;
		this.masoThue = masoThue;
		this.diaChi = diaChi;
		this.dienthoai = dienthoai;
		this.email = email;
		this.tiLeMakeUp = tiLeMakeUp;
//		this.dausos = dausos;
//		this.phongbans = phongbans;
//		this.taikhoanNguoidungs = taikhoanNguoidungs;
	}

	public Congty() {
		super();
	}

	@Id

	@Column(name = "congtyID", unique = true, nullable = false, length = 10)
	public String getCongtyId() {
		return this.congtyId;
	}

	public void setCongtyId(String congtyId) {
		this.congtyId = congtyId;
	}

	@Column(name = "ten_congty", length = 65535)
	public String getTenCongty() {
		return this.tenCongty;
	}

	public void setTenCongty(String tenCongty) {
		this.tenCongty = tenCongty;
	}

	@Column(name = "logo", length = 65535)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "maso_thue", length = 65535)
	public String getMasoThue() {
		return this.masoThue;
	}

	public void setMasoThue(String masoThue) {
		this.masoThue = masoThue;
	}

	@Column(name = "dia_chi", length = 65535)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "dienthoai", length = 65535)
	public String getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(String dienthoai) {
		this.dienthoai = dienthoai;
	}

	@Column(name = "email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ti_le_make_up", precision = 22, scale = 0)
	public Double getTiLeMakeUp() {
		return this.tiLeMakeUp;
	}

	public void setTiLeMakeUp(Double tiLeMakeUp) {
		this.tiLeMakeUp = tiLeMakeUp;
	}

	
	

	@Override
	public String toString() {
		return "Congty [congtyId=" + congtyId + ", tenCongty=" + tenCongty + ", logo=" + logo + ", masoThue=" + masoThue
				+ ", diaChi=" + diaChi + ", dienthoai=" + dienthoai + ", email=" + email + ", tiLeMakeUp=" + tiLeMakeUp
				+ "]";
	}

	

	
	

	

	
	


	

	
}
