package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dauso generated by hbm2java
 */
@Entity
@Table(name = "dauso", catalog = "billings")
public class Dauso implements java.io.Serializable {

	private String dausoSudung;
	private Congty congty;
	private String nhamangId;

	public Dauso() {
	}

	public Dauso(String dausoSudung) {
		this.dausoSudung = dausoSudung;
	}

	public Dauso(String dausoSudung, Congty congty, String nhamangId) {
		this.dausoSudung = dausoSudung;
		this.congty = congty;
		this.nhamangId = nhamangId;
	}

	@Id

	@Column(name = "dauso_sudung", unique = true, nullable = false, length = 20)
	public String getDausoSudung() {
		return this.dausoSudung;
	}

	public void setDausoSudung(String dausoSudung) {
		this.dausoSudung = dausoSudung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "congtyID")
	public Congty getCongty() {
		return this.congty;
	}

	public void setCongty(Congty congty) {
		this.congty = congty;
	}

	@Column(name = "nhamang_id", length = 5)
	public String getNhamangId() {
		return this.nhamangId;
	}

	public void setNhamangId(String nhamangId) {
		this.nhamangId = nhamangId;
	}

}
