package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LogCall generated by hbm2java
 */
@Entity
@Table(name = "log_call", catalog = "billings")
public class LogCall implements java.io.Serializable {

	private Integer logId;
	private Extension extension;
	private String thuebaonhan;
	private Integer thoigianGoi;
	private Double giaTien;
	private String loaiCuocgoi;
	private String nhamangId;
	private String maCuocgoi;

	public LogCall() {
	}

	public LogCall(Extension extension, String thuebaonhan, Integer thoigianGoi, Double giaTien, String loaiCuocgoi,
			String nhamangId, String maCuocgoi) {
		this.extension = extension;
		this.thuebaonhan = thuebaonhan;
		this.thoigianGoi = thoigianGoi;
		this.giaTien = giaTien;
		this.loaiCuocgoi = loaiCuocgoi;
		this.nhamangId = nhamangId;
		this.maCuocgoi = maCuocgoi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extensionID")
	public Extension getExtension() {
		return this.extension;
	}

	public void setExtension(Extension extension) {
		this.extension = extension;
	}

	@Column(name = "thuebaonhan", length = 65535)
	public String getThuebaonhan() {
		return this.thuebaonhan;
	}

	public void setThuebaonhan(String thuebaonhan) {
		this.thuebaonhan = thuebaonhan;
	}

	@Column(name = "thoigian_goi")
	public Integer getThoigianGoi() {
		return this.thoigianGoi;
	}

	public void setThoigianGoi(Integer thoigianGoi) {
		this.thoigianGoi = thoigianGoi;
	}

	@Column(name = "gia_tien", precision = 22, scale = 0)
	public Double getGiaTien() {
		return this.giaTien;
	}

	public void setGiaTien(Double giaTien) {
		this.giaTien = giaTien;
	}

	@Column(name = "loai_cuocgoi", length = 2)
	public String getLoaiCuocgoi() {
		return this.loaiCuocgoi;
	}

	public void setLoaiCuocgoi(String loaiCuocgoi) {
		this.loaiCuocgoi = loaiCuocgoi;
	}

	@Column(name = "nhamang_id", length = 5)
	public String getNhamangId() {
		return this.nhamangId;
	}

	public void setNhamangId(String nhamangId) {
		this.nhamangId = nhamangId;
	}

	@Column(name = "ma_cuocgoi", length = 5)
	public String getMaCuocgoi() {
		return this.maCuocgoi;
	}

	public void setMaCuocgoi(String maCuocgoi) {
		this.maCuocgoi = maCuocgoi;
	}

}
