package com.athl.model;
// Generated Dec 6, 2017 10:05:40 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaikhoanNguoidung generated by hbm2java
 */
@Entity
@Table(name = "taikhoan_nguoidung")
public class TaikhoanNguoidung implements java.io.Serializable {

	private String username;
	private Congty congty;
	private String userpass;
	private Integer role;

	public TaikhoanNguoidung() {
	}

	public TaikhoanNguoidung(String username) {
		this.username = username;
	}

	public TaikhoanNguoidung(String username, Congty congty, String userpass, Integer role) {
		this.username = username;
		this.congty = congty;
		this.userpass = userpass;
		this.role = role;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "congtyID")
	public Congty getCongty() {
		return this.congty;
	}

	public void setCongty(Congty congty) {
		this.congty = congty;
	}

	@Column(name = "userpass", length = 65535)
	public String getUserpass() {
		return this.userpass;
	}

	public void setUserpass(String userpass) {
		this.userpass = userpass;
	}

	@Column(name = "role")
	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

}
